// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use signal_persona::schema::lib::ComponentName as ComponentName;
#[rustfmt::skip]
pub use signal_persona::schema::lib::EngineIdentifier as EngineIdentifier;
#[rustfmt::skip]
pub use signal_persona::schema::lib::OwnerIdentity as OwnerIdentity;
#[rustfmt::skip]
pub use signal_message::schema::lib::MessageSlot as MessageIdentifier;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum IntrospectionTarget {
    EngineManager,
    Mind,
    Message,
    Router,
    Spirit,
    System,
    Harness,
    Terminal,
    Introspect,
    Signal,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum IntrospectionScope {
    EngineSnapshot,
    ComponentSnapshot,
    DeliveryTrace,
    PrototypeWitness,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineSnapshotQuery(EngineIdentifier);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentSnapshotQuery {
    pub engine_identifier: EngineIdentifier,
    pub introspection_target: IntrospectionTarget,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeliveryTraceQuery {
    pub engine_identifier: EngineIdentifier,
    pub message_identifier: MessageIdentifier,
    pub component_name: ComponentName,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PrototypeWitnessQuery(EngineIdentifier);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObservedComponents(Vec<IntrospectionTarget>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineSnapshot {
    pub engine_identifier: EngineIdentifier,
    pub observed_components: ObservedComponents,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentSnapshot {
    pub engine_identifier: EngineIdentifier,
    pub introspection_target: IntrospectionTarget,
    pub optional_component_readiness: Option<ComponentReadiness>,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ComponentReadiness {
    Ready,
    NotReady,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HopIndex(u32);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeliveryTraceJoinKey {
    pub engine_identifier: EngineIdentifier,
    pub message_identifier: MessageIdentifier,
    pub component_name: ComponentName,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeliveryTraceKey {
    pub engine_identifier: EngineIdentifier,
    pub message_identifier: MessageIdentifier,
    pub component_name: ComponentName,
    pub hop_index: HopIndex,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeliveryTraceEvent {
    pub delivery_trace_key: DeliveryTraceKey,
    pub component_name: ComponentName,
    pub delivery_trace_status: DeliveryTraceStatus,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeliveryTraceEvents(Vec<DeliveryTraceEvent>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeliveryTrace {
    pub engine_identifier: EngineIdentifier,
    pub message_identifier: MessageIdentifier,
    pub component_name: ComponentName,
    pub delivery_trace_events: DeliveryTraceEvents,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum DeliveryTraceStatus {
    Accepted,
    Routed,
    Delivered,
    Deferred,
    Failed,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PrototypeWitness {
    pub engine_identifier: EngineIdentifier,
    pub manager_seen: Option<ComponentReadiness>,
    pub router_seen: Option<ComponentReadiness>,
    pub terminal_seen: Option<ComponentReadiness>,
    pub optional_delivery_trace_status: Option<DeliveryTraceStatus>,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IntrospectionUnimplemented {
    pub introspection_scope: IntrospectionScope,
    pub introspection_unimplemented_reason: IntrospectionUnimplementedReason,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum IntrospectionUnimplementedReason {
    NotInPrototypeScope,
    ComponentObservationMissing,
    SubscriptionNotImplemented,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IntrospectionDenied {
    pub introspection_scope: IntrospectionScope,
    pub introspection_denied_reason: IntrospectionDeniedReason,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum IntrospectionDeniedReason {
    NotAuthorized,
    Redacted,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TraceEventName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TraceSequence(u64);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum TraceLayer {
    Signal,
    Nexus,
    Sema,
    Authorization,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentTraceEvent {
    pub engine_identifier: EngineIdentifier,
    pub introspection_target: IntrospectionTarget,
    pub trace_layer: TraceLayer,
    pub trace_event_name: TraceEventName,
    pub trace_sequence: TraceSequence,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentTraceQuery {
    pub engine_identifier: EngineIdentifier,
    pub introspection_target: IntrospectionTarget,
    pub optional_trace_event_name: Option<TraceEventName>,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentTraceEvents(Vec<ComponentTraceEvent>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentTrace {
    pub engine_identifier: EngineIdentifier,
    pub introspection_target: IntrospectionTarget,
    pub component_trace_events: ComponentTraceEvents,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WirePath(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SocketMode(u64);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IntrospectDaemonConfiguration {
    pub introspect_socket_path: WirePath,
    pub introspect_socket_mode: SocketMode,
    pub supervision_socket_path: WirePath,
    pub supervision_socket_mode: SocketMode,
    pub store_path: WirePath,
    pub manager_socket_path: WirePath,
    pub router_socket_path: WirePath,
    pub terminal_socket_path: WirePath,
    pub trace_socket_path: WirePath,
    pub owner_identity: OwnerIdentity,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    EngineSnapshot(EngineSnapshotQuery),
    ComponentSnapshot(ComponentSnapshotQuery),
    DeliveryTrace(DeliveryTraceQuery),
    PrototypeWitness(PrototypeWitnessQuery),
    ComponentTrace(ComponentTraceQuery),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    EngineSnapshot(EngineSnapshot),
    ComponentSnapshot(ComponentSnapshot),
    DeliveryTrace(DeliveryTrace),
    PrototypeWitness(PrototypeWitness),
    ComponentTrace(ComponentTrace),
    Unimplemented(IntrospectionUnimplemented),
    Denied(IntrospectionDenied),
}

#[rustfmt::skip]
impl EngineSnapshotQuery {
    pub fn new(payload: EngineIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &EngineIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> EngineIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<EngineIdentifier> for EngineSnapshotQuery {
    fn from(payload: EngineIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PrototypeWitnessQuery {
    pub fn new(payload: EngineIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &EngineIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> EngineIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<EngineIdentifier> for PrototypeWitnessQuery {
    fn from(payload: EngineIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ObservedComponents {
    pub fn new(payload: Vec<IntrospectionTarget>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<IntrospectionTarget> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<IntrospectionTarget> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<IntrospectionTarget>> for ObservedComponents {
    fn from(payload: Vec<IntrospectionTarget>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl HopIndex {
    pub fn new(payload: u32) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &u32 {
        &self.0
    }
    pub fn into_payload(self) -> u32 {
        self.0
    }
}
#[rustfmt::skip]
impl From<u32> for HopIndex {
    fn from(payload: u32) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeliveryTraceEvents {
    pub fn new(payload: Vec<DeliveryTraceEvent>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<DeliveryTraceEvent> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<DeliveryTraceEvent> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<DeliveryTraceEvent>> for DeliveryTraceEvents {
    fn from(payload: Vec<DeliveryTraceEvent>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TraceEventName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for TraceEventName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TraceSequence {
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
#[rustfmt::skip]
impl From<u64> for TraceSequence {
    fn from(payload: u64) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ComponentTraceEvents {
    pub fn new(payload: Vec<ComponentTraceEvent>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ComponentTraceEvent> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ComponentTraceEvent> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ComponentTraceEvent>> for ComponentTraceEvents {
    fn from(payload: Vec<ComponentTraceEvent>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WirePath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for WirePath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SocketMode {
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
#[rustfmt::skip]
impl From<u64> for SocketMode {
    fn from(payload: u64) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn engine_snapshot(payload: EngineIdentifier) -> Self {
        Self::EngineSnapshot(EngineSnapshotQuery::new(payload))
    }
    pub fn component_snapshot(payload: ComponentSnapshotQuery) -> Self {
        Self::ComponentSnapshot(payload)
    }
    pub fn delivery_trace(payload: DeliveryTraceQuery) -> Self {
        Self::DeliveryTrace(payload)
    }
    pub fn prototype_witness(payload: EngineIdentifier) -> Self {
        Self::PrototypeWitness(PrototypeWitnessQuery::new(payload))
    }
    pub fn component_trace(payload: ComponentTraceQuery) -> Self {
        Self::ComponentTrace(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn engine_snapshot(payload: EngineSnapshot) -> Self {
        Self::EngineSnapshot(payload)
    }
    pub fn component_snapshot(payload: ComponentSnapshot) -> Self {
        Self::ComponentSnapshot(payload)
    }
    pub fn delivery_trace(payload: DeliveryTrace) -> Self {
        Self::DeliveryTrace(payload)
    }
    pub fn prototype_witness(payload: PrototypeWitness) -> Self {
        Self::PrototypeWitness(payload)
    }
    pub fn component_trace(payload: ComponentTrace) -> Self {
        Self::ComponentTrace(payload)
    }
    pub fn unimplemented(payload: IntrospectionUnimplemented) -> Self {
        Self::Unimplemented(payload)
    }
    pub fn denied(payload: IntrospectionDenied) -> Self {
        Self::Denied(payload)
    }
}

#[rustfmt::skip]
impl From<EngineSnapshotQuery> for Input {
    fn from(payload: EngineSnapshotQuery) -> Self {
        Self::EngineSnapshot(payload)
    }
}

#[rustfmt::skip]
impl From<ComponentSnapshotQuery> for Input {
    fn from(payload: ComponentSnapshotQuery) -> Self {
        Self::ComponentSnapshot(payload)
    }
}

#[rustfmt::skip]
impl From<DeliveryTraceQuery> for Input {
    fn from(payload: DeliveryTraceQuery) -> Self {
        Self::DeliveryTrace(payload)
    }
}

#[rustfmt::skip]
impl From<PrototypeWitnessQuery> for Input {
    fn from(payload: PrototypeWitnessQuery) -> Self {
        Self::PrototypeWitness(payload)
    }
}

#[rustfmt::skip]
impl From<ComponentTraceQuery> for Input {
    fn from(payload: ComponentTraceQuery) -> Self {
        Self::ComponentTrace(payload)
    }
}

#[rustfmt::skip]
impl From<EngineSnapshot> for Output {
    fn from(payload: EngineSnapshot) -> Self {
        Self::EngineSnapshot(payload)
    }
}

#[rustfmt::skip]
impl From<ComponentSnapshot> for Output {
    fn from(payload: ComponentSnapshot) -> Self {
        Self::ComponentSnapshot(payload)
    }
}

#[rustfmt::skip]
impl From<DeliveryTrace> for Output {
    fn from(payload: DeliveryTrace) -> Self {
        Self::DeliveryTrace(payload)
    }
}

#[rustfmt::skip]
impl From<PrototypeWitness> for Output {
    fn from(payload: PrototypeWitness) -> Self {
        Self::PrototypeWitness(payload)
    }
}

#[rustfmt::skip]
impl From<ComponentTrace> for Output {
    fn from(payload: ComponentTrace) -> Self {
        Self::ComponentTrace(payload)
    }
}

#[rustfmt::skip]
impl From<IntrospectionUnimplemented> for Output {
    fn from(payload: IntrospectionUnimplemented) -> Self {
        Self::Unimplemented(payload)
    }
}

#[rustfmt::skip]
impl From<IntrospectionDenied> for Output {
    fn from(payload: IntrospectionDenied) -> Self {
        Self::Denied(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_ENGINE_SNAPSHOT: u64 = 0x0000000000000000;
    pub const INPUT_COMPONENT_SNAPSHOT: u64 = 0x0001000000000000;
    pub const INPUT_DELIVERY_TRACE: u64 = 0x0002000000000000;
    pub const INPUT_PROTOTYPE_WITNESS: u64 = 0x0003000000000000;
    pub const INPUT_COMPONENT_TRACE: u64 = 0x0004000000000000;
    pub const OUTPUT_ENGINE_SNAPSHOT: u64 = 0x0100000000000000;
    pub const OUTPUT_COMPONENT_SNAPSHOT: u64 = 0x0101000000000000;
    pub const OUTPUT_DELIVERY_TRACE: u64 = 0x0102000000000000;
    pub const OUTPUT_PROTOTYPE_WITNESS: u64 = 0x0103000000000000;
    pub const OUTPUT_COMPONENT_TRACE: u64 = 0x0104000000000000;
    pub const OUTPUT_UNIMPLEMENTED: u64 = 0x0105000000000000;
    pub const OUTPUT_DENIED: u64 = 0x0106000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    EngineSnapshot,
    ComponentSnapshot,
    DeliveryTrace,
    PrototypeWitness,
    ComponentTrace,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    EngineSnapshot,
    ComponentSnapshot,
    DeliveryTrace,
    PrototypeWitness,
    ComponentTrace,
    Unimplemented,
    Denied,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::EngineSnapshot(_) => InputRoute::EngineSnapshot,
            Self::ComponentSnapshot(_) => InputRoute::ComponentSnapshot,
            Self::DeliveryTrace(_) => InputRoute::DeliveryTrace,
            Self::PrototypeWitness(_) => InputRoute::PrototypeWitness,
            Self::ComponentTrace(_) => InputRoute::ComponentTrace,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::EngineSnapshot(_) => short_header::INPUT_ENGINE_SNAPSHOT,
            Self::ComponentSnapshot(_) => short_header::INPUT_COMPONENT_SNAPSHOT,
            Self::DeliveryTrace(_) => short_header::INPUT_DELIVERY_TRACE,
            Self::PrototypeWitness(_) => short_header::INPUT_PROTOTYPE_WITNESS,
            Self::ComponentTrace(_) => short_header::INPUT_COMPONENT_TRACE,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_ENGINE_SNAPSHOT => Ok(InputRoute::EngineSnapshot),
            short_header::INPUT_COMPONENT_SNAPSHOT => Ok(InputRoute::ComponentSnapshot),
            short_header::INPUT_DELIVERY_TRACE => Ok(InputRoute::DeliveryTrace),
            short_header::INPUT_PROTOTYPE_WITNESS => Ok(InputRoute::PrototypeWitness),
            short_header::INPUT_COMPONENT_TRACE => Ok(InputRoute::ComponentTrace),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::EngineSnapshot(_) => OutputRoute::EngineSnapshot,
            Self::ComponentSnapshot(_) => OutputRoute::ComponentSnapshot,
            Self::DeliveryTrace(_) => OutputRoute::DeliveryTrace,
            Self::PrototypeWitness(_) => OutputRoute::PrototypeWitness,
            Self::ComponentTrace(_) => OutputRoute::ComponentTrace,
            Self::Unimplemented(_) => OutputRoute::Unimplemented,
            Self::Denied(_) => OutputRoute::Denied,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::EngineSnapshot(_) => short_header::OUTPUT_ENGINE_SNAPSHOT,
            Self::ComponentSnapshot(_) => short_header::OUTPUT_COMPONENT_SNAPSHOT,
            Self::DeliveryTrace(_) => short_header::OUTPUT_DELIVERY_TRACE,
            Self::PrototypeWitness(_) => short_header::OUTPUT_PROTOTYPE_WITNESS,
            Self::ComponentTrace(_) => short_header::OUTPUT_COMPONENT_TRACE,
            Self::Unimplemented(_) => short_header::OUTPUT_UNIMPLEMENTED,
            Self::Denied(_) => short_header::OUTPUT_DENIED,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_ENGINE_SNAPSHOT => Ok(OutputRoute::EngineSnapshot),
            short_header::OUTPUT_COMPONENT_SNAPSHOT => Ok(OutputRoute::ComponentSnapshot),
            short_header::OUTPUT_DELIVERY_TRACE => Ok(OutputRoute::DeliveryTrace),
            short_header::OUTPUT_PROTOTYPE_WITNESS => Ok(OutputRoute::PrototypeWitness),
            short_header::OUTPUT_COMPONENT_TRACE => Ok(OutputRoute::ComponentTrace),
            short_header::OUTPUT_UNIMPLEMENTED => Ok(OutputRoute::Unimplemented),
            short_header::OUTPUT_DENIED => Ok(OutputRoute::Denied),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "EngineSnapshot",
        "ComponentSnapshot",
        "DeliveryTrace",
        "PrototypeWitness",
        "ComponentTrace",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}
